pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://android-sdk.is.com/' }

        maven {
            url = uri("https://maven.pkg.github.com/z0ro25/FSD-ADS")
            credentials {
                username = providers.gradleProperty("GITHUB_USERNAME").orElse("").get()
                password = providers.gradleProperty("GITHUB_TOKEN").orElse("").get()
            }
        }
    }
}

rootProject.name = "FSD-BASE-AND"
include ':app'
