plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id 'com.google.firebase.crashlytics'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.truongnt.fsd.fsd_base_and'
    compileSdk 36

    defaultConfig {
        applicationId "com.truongnt.fsd.fsd_base_and"
        minSdk 26
        targetSdk 36
        versionCode 100
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        def formattedDate = new Date().format('MM.dd.yyyy')
        archivesBaseName = "base_v${versionName}_${formattedDate}"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures{
        buildConfig true
    }

    buildFeatures{
        viewBinding true
    }

    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    //lottie
    implementation "com.airbnb.android:lottie:6.6.7"

    //play core
    implementation 'com.google.android.play:review:2.0.2'

    // WindowManager
    implementation 'androidx.window:window:1.1.0-alpha03'

    //glide
    implementation("com.github.bumptech.glide:glide:4.13.2")
    annotationProcessor("com.github.bumptech.glide:compiler:4.12.0")

    implementation 'com.github.ome450901:SimpleRatingBar:1.5.1'

    //serializable
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")
    implementation 'com.google.code.gson:gson:2.10.1'

    //billing
    implementation 'com.android.billingclient:billing-ktx:8.0.0'
    implementation("com.tbuonomo:dotsindicator:5.1.0")

    //firebase
    implementation platform('com.google.firebase:firebase-bom:30.1.0')
    implementation 'com.google.firebase:firebase-analytics:19.0.0'
    implementation 'com.google.firebase:firebase-messaging:23.4.0'
    implementation 'com.google.firebase:firebase-crashlytics:18.6.0'
    implementation 'com.google.firebase:firebase-config:21.6.0'

    implementation 'com.google.android.ump:user-messaging-platform:3.2.0'

    //ads
    implementation 'com.google.android.gms:play-services-ads:24.6.0'
    implementation 'com.truongnt.fsd:fsdads:1.1.32'
}